
# ---------------------------------------------------------------------------- #
#                                Default profile                               #
# ---------------------------------------------------------------------------- #

[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
# -------------------------------- Remappings -------------------------------- #
remappings = ["forge-std/=dependencies/forge-std-1.14.0/src/"]

[dependencies]
forge-std = "1.14.0"


# ---------------------------------------------------------------------------- #
#                                    Soldeer                                   #
# ---------------------------------------------------------------------------- #

[soldeer]
remappings_location = "config"
recursive_deps = true
